---
name: Checks

#trigger for git changes
on: [push]

jobs:
    test-lint:
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps:
            # Log into Docker Hub
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secretes.DOCKERHUB_USERNAME }}
                  password: ${{ secretes.DOCKERHUB_TOKEN }}

            #checkout
            - name: Checkout
              uses: actions/checkout@v2

            #run test
            - name: Test
              run: docker-compose run --rm app sh -c "python manage.py test"

            #run linting
            - name: Lint
              run: docker-compose run --rm app sh -c "flake8"